# Generated by Django 3.2 on 2021-05-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_photo_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='privacy',
            field=models.BooleanField(),
        ),
    ]
