# Generated by Django 3.2 on 2021-05-06 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210505_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interaction',
            old_name='author',
            new_name='user',
        ),
    ]
