# Generated by Django 3.2 on 2021-05-06 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_author_interaction_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interaction',
            old_name='interaction_type',
            new_name='interaction',
        ),
    ]
